volumes:
  web:
services:
  fhircapstoneproject:
    build:
      context: .
      dockerfile: FhirCapstoneProject/Dockerfile
    restart: always
    ports:
      - '5000:5000'
    command: gunicorn -b 0.0.0.0:5000 --timeout 3000 FhirCapstoneProject.swaggerUI.app:app
  frontend:
    build:
      context: FrontEnd
    environment:
      NODE_ENV: production
      VITE_API_BASE_URL: http://fhircapstoneproject:5000/api/getdata
    ports:
      - 8080:8080
    depends_on:
      - fhircapstoneproject
  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    depends_on:
      - fhircapstoneproject
    environment:
      DOCS_STATIC: /documentation/output/
    volumes:
      - web:/documentation/output/
  reverseproxy:
    build:
      context: .
      dockerfile: ReverseProxy/Dockerfile
    restart: always
    environment:
      API_BASE_URL: http://fhircapstoneproject:5000
      FRONTEND_BASE_URL: http://frontend:8080
      DOCS_STATIC: /documentation/output/
    volumes:
      - web:/documentation/output/
      - ./nginx/default.conf:/tmp/default.conf
    depends_on:
      - frontend
      - docs
    ports:
      - 80:80
    command: /app/start.sh