services:
  fhircapstoneproject:
    build:
      context: .
      dockerfile: FhirCapstoneProject/Dockerfile
    ports:
      - 8000:8000
  frontend:
    build:
      context: FrontEnd
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    depends_on:
      - fhircapstoneproject
  reverseproxy:
    build:
      context: .
      dockerfile: ReverseProxy/Dockerfile
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    depends_on:
      - frontend
#    command: bash ./start.sh