services:
  fhircapstoneproject:
    build:
      context: .
      dockerfile: FhirCapstoneProject/Dockerfile
    restart: always
    ports:
      - '5000:5000'
    command: gunicorn -b 0.0.0.0:5000 --timeout 3000 FhirCapstoneProject.swaggerUI.app:app
  frontend:
    build:
      context: FrontEnd
    environment:
      NODE_ENV: production
      VITE_API_BASE_URL: http://fhircapstoneproject:5000/api/getdata
    ports:
      - 8080:8080
    depends_on:
      - fhircapstoneproject
  reverseproxy:
    build:
      context: .
      dockerfile: ReverseProxy/Dockerfile
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    depends_on:
      - frontend
    ports:
      - 80:80