volumes:
  web:
services:
  fhircapstoneproject:
    build:
      context: .
      dockerfile: FhirCapstoneProject/Dockerfile
    restart: always
    ports:
      - ${PORT_API}
    command: gunicorn -b 0.0.0.0:${PORT_API} --timeout 3000 FhirCapstoneProject.swaggerUI.app:app
  frontend:
    build:
      context: FrontEnd
    environment:
      NODE_ENV: ${NODE_ENV}
      BASE_HOST: ${BASE_HOST}
      VITE_API_GETDATA_URL: ${VITE_API_GETDATA_URL}
      # See DockerFile for API get data url (also refer to .env)
    depends_on:
      - fhircapstoneproject
  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    environment:
      DOCS_STATIC: ${DOCS_STATIC}
    depends_on:
      - fhircapstoneproject
    volumes:
      - web:${DOCS_STATIC}
  reverseproxy:
    build:
      context: .
      dockerfile: ReverseProxy/Dockerfile
    restart: always
    environment:
      NGINX_API_BASE_URL: ${NGINX_API_BASE_URL}
      NGINX_FRONTEND_BASE_URL: ${NGINX_FRONTEND_BASE_URL}
      SUBDOMAIN_API: ${SUBDOMAIN_API}
      SUBDOMAIN_DOCUMENTATION: ${SUBDOMAIN_DOCUMENTATION}
      BASE_HOST: ${BASE_HOST}
      DOCS_STATIC: ${DOCS_STATIC}
    volumes:
      - web:${DOCS_STATIC}
      - ./nginx/default.conf:/tmp/default.conf
    depends_on:
      - frontend
      - docs
    ports:
      - 80:80
    command: /bin/bash /app/start.sh