# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: FHIRType Development Deployment

on:
  pull_request:
    branches: [ "Dev" ]

permissions:
  contents: write

jobs:
  dev_pr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint diff with BLACK
      run : |
        # show diffs, consider linting if there are a lot of changes
        black --verbose --diff --color FhirCapstoneProject
    - name: Generate config files
      run : python src/configMaker.py -endpoints Endpoints FhirCapstoneProject/fhirtypepkg/config/default_endpoints.txt -logger Logging blank
