# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: FHIRType Production Deployment

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  prod_pr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black
        if [ -f requirements.txt ]; then pip install -r requirements/prod.txt; fi
    - name: Generate config files
      run : python FhirCapstoneProject/configMaker.py -endpoints Endpoints FhirCapstoneProject/fhirtypepkg/config/default_endpoints.txt -logger Logging blank
    - name: Test with pytest
      run: |
        pytest